### ISSUE TITLE
同人誌のタイトルを決める

### ISSUE THREAD

**Issue by hyoiutu** [hyoiutu/techbookfest_localstudents_2017#27]
同人誌のタイトルが「やばい同人誌執筆合宿」のままになっている

**Comment by takuzoo3868** [comment]
何がいいですかね？

**Comment by aruneko** [comment]
なんか最近はやりの技術書とかってありましたっけ

**Comment by takuzoo3868** [comment]
この辺かなと

![screenshot_20180401-225443](https://user-images.githubusercontent.com/18602067/38173876-d5069a9c-35ff-11e8-83bf-be1867a705a1.png)

**Comment by aruneko** [comment]
"退屈なことは～"
でうまいことできたら面白そう

**Comment by takuzoo3868** [comment]
Automate the Boring Stuff with LOCAL
うーん...なんかイマイチですかね...

**Comment by lrf141** [comment]
一応、LOCAL学生部のslackで書く前からタイトルこんなんでどう？みたいなの色々出ていたので挙げておきます
- 熱血コンピュータ理論　監修：LOCAL学生部の愉快な仲間たち
- ゼロから始めるコンピュータ生活
- コンピュータと画家をもじってコンピュータと馬鹿
Tehu君先生の世界にひとつだけの授業をもじって
- LOCAL学生部の世界にひとつだけの授業
- 基本演習　コンピュータ　初版
- 世界で一番簡単なコンピュータ理論のe本
- LOCAL学生部と馬鹿 コンピュータ時代の創造者たち
- 情報ボーイズの寄稿ノート
- タイトル「こんなんでどうでしょう」
（水曜どうでしょうをもじって）

**Comment by aruneko** [comment]
では「情報ボーイズの寄稿ノート」の方向で行きましょう

**Comment by hyoiutu** [comment]
タイトルを表紙に反映させた

**Comment by takuzoo3868** [comment]
解決したという事でクローズします．
