### ISSUE TITLE
画像とソースコードのグレースケール化

### ISSUE THREAD

**Issue by aruneko** [hyoiutu/techbookfest_localstudents_2017#29]
白黒印刷する場合は入稿時にすでに白黒になっていなければいけないようです。
画像は600dpiの白黒画像にして欲しいそうなので、変換する作業があります。

ソースコードの方はどうしましょうね。

**Comment by hyoiutu** [comment]
ソースコードはグレースケール化した

**Comment by aruneko** [comment]
とりあえずグレースケール画像は準備したので、引き続いて画像の差し替え作業をします。

**Comment by aruneko** [comment]
close #33
