### ISSUE TITLE
最後のページなんとかする

### ISSUE THREAD

**Issue by hyoiutu** [hyoiutu/techbookfest_localstudents_2017#35]
最後のページのタイトル，著者，挿絵，発行，印刷の項目を正確にする

**Comment by hyoiutu** [comment]
少し修正してみた

**Comment by aruneko** [comment]
https://github.com/hyoiutu/techbookfest_localstudents_2017/commit/a1763657106aeab3870a11a67fa1658c7f32bf98 でちょっと奥付を直してみました。
特に記載の無いソースコードに関してはCC BY 4.0を適用しようと思います。
